export const LOADING_EXPENSES = "LOADING_EXPENSES";
export const LOADED_EXPENSES = "LOADED_EXPENSES";

export const ADDING_EXPENSE = "ADDING_EXPENSE";
export const ADD_EXPENSE = "ADD_EXPENSE";

export const DELETING_EXPENSE = "DELETING_EXPENSE";
export const DELETE_EXPENSE = "DELETE_EXPENSE;";
export const DELETE_ALL_EXPENSES = "DELETE_ALL_EXPENSES"